language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
